# Change these first
owner: dylan-da # Your GitHub organization or username, where this repository lives
repo: ayoba-microapp-uptime-monitor # The name of this repository

sites:
  - name: Survey54
    url: https://survey54.com/open-surveys
  - name: Guardian Health
    url: https://guardianhealth.io/
  - name: Samestart
    url: https://www.samestart.com/
  - name: playboxcade
    url: https://playboxcade.com/
  - name: Firework
    url: https://fw.tv/ayoba_africa
  - name: Miss Côte d Ivoire 2021
    url: https://www.mtn.ci/miss-ci/
  - name: Live Masjid
    url: https://www.livemasjid.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /ayoba-microapp-uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Ayoba Microapp Uptime Tracker**"
  introMessage: An app using github actions to track the uptime of ayoba microapps
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
